### ISSUE TITLE
In counter have a set value option

### ISSUE THREAD

**Issue by Robbo312** [Docoyo/node-red-contrib-prometheus-exporter#12]
Would be handy to have a set value option in the counter like guage.   The source I'm using (Total kWh in a energy meter) so I just need to set the value not increase it by a certain amount.

**Comment by jdeisenh** [comment]
Seconded. 
It's not only handy, but necessary if you want to pass through counters that originate somewhere else. 
Making them gauges is simply not an option, it won't handle resets correctly, which is the whole point of having counters.

**Comment by hashworks** [comment]
#19 solves this by adding a reset parameter, which, if set, resets the metric before the operation. This way this payload behaves like a `set` operation:
```javascript
{
    reset: true,
    op: "inc",
    val: 5000,
}
```
