### ISSUE TITLE
No data in metrics

### ISSUE THREAD

**Issue by ksga** [Docoyo/node-red-contrib-prometheus-exporter#14]
I can't seem to get any output to my Node-RED metrics page.

I've setup a single counter output setup, fed by a Inject node (firing every second) through a Template node:
`[{"id":"271e5e391962b383","type":"inject","z":"cae39ee2.e2c898","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":true,"onceDelay":0.1,"topic":"","payloadType":"date","x":340,"y":200,"wires":[["b74cf7ca73e55ee4"]]},{"id":"b74cf7ca73e55ee4","type":"template","z":"cae39ee2.e2c898","name":"","field":"payload","fieldType":"msg","format":"json","syntax":"plain","template":"{\n    \"op\": \"inc\"\n}","output":"str","x":560,"y":100,"wires":[["ea8507f4388b7b5f","106518794a79dd30"]]},{"id":"ea8507f4388b7b5f","type":"prometheus-exporter","z":"cae39ee2.e2c898","name":"metric_temp-BK","metric":"f7b80ed39105d802","x":740,"y":100,"wires":[]},{"id":"f7b80ed39105d802","type":"prometheus-metric-config","name":"temp-BK","help":"Boil kettle temperaure","labels":"","mtype":"counter"}]`

Am I missing something? 
The SERVERIP:1880/metrics page is simply blank.

Everything is running directly on metal - no docker, iptables or anything else set.

Program versions:
node-red-contrib-prometheus-exporter v1.0.5

Prometheus version:
prometheus, version 2.29.1 (branch: HEAD, revision: dcb07e8eac34b5ea37cd229545000b857f1c1637)
  build user:       root@9f54ccae6d42
  build date:       20210811-14:38:07
  go version:       go1.16.7
  platform:         linux/arm

node_exporter, version 1.2.2 (branch: HEAD, revision: 26645363b486e12be40af7ce4fc91e731a33104e)
  build user:       root@1c3411405b8f
  build date:       20210806-13:43:27
  go version:       go1.16.7
  platform:         linux/arm

Node-RED version: v2.0.5
Node.js  version: v14.17.3
Linux 5.10.52+ arm LE

Running on RPi Zero W
Linux raspberrypi 5.10.52+ #1441 Tue Aug 3 18:08:18 BST 2021 armv6l GNU/Linux

**Comment by matterlobby** [comment]
I checked your flow and am seeing that you are using a template node to create a string-typed output which in turn gets injected into the prometheus-metrics-node. This won't work because the prometheus-metrics-node is expecting a plain JS object as input in payload. So you simply need to omit the template node and create the payload body in the Inject Node itself.

Please try this example:

`[
    {
        "id": "950910c05b240c42",
        "type": "tab",
        "label": "Prometheus Metrics Test",
        "disabled": false,
        "info": ""
    },
    {
        "id": "a79d0509fe0ead6e",
        "type": "prometheus-exporter",
        "z": "950910c05b240c42",
        "name": "",
        "metric": "a1df1a8b7573f3c3",
        "x": 410,
        "y": 100,
        "wires": []
    },
    {
        "id": "b28be1b0e26782cc",
        "type": "inject",
        "z": "950910c05b240c42",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"op\":\"inc\"}",
        "payloadType": "json",
        "x": 170,
        "y": 100,
        "wires": [
            [
                "a79d0509fe0ead6e"
            ]
        ]
    },
    {
        "id": "a1df1a8b7573f3c3",
        "type": "prometheus-metric-config",
        "name": "masa_counter_1",
        "help": "Test Counter 1",
        "labels": "",
        "mtype": "counter"
    }
]`

**Comment by ksga** [comment]
Thanks @matterlobby 
You got me in the right direction :)

So - I think the first mistake was actually using a "-" in the prometheus-metric-config name.
I switched it to a "_" and it showed up in /metrics alongside your test flow.

Then I went back and changed the Template node for a Function, and now it works as I want it to as a Gauge👯‍♀️ 

`[{"id":"91058b9e16804d6c","type":"inject","z":"cae39ee2.e2c898","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"22.54","payloadType":"num","x":90,"y":180,"wires":[["35c57d02fdc45ba3"]]},{"id":"35c57d02fdc45ba3","type":"function","z":"cae39ee2.e2c898","name":"","func":"msg.payload = {\n         \"op\": \"set\",\n         \"val\": msg.payload\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":280,"y":180,"wires":[["ea8507f4388b7b5f","0db42fce15bb0aac"]]},{"id":"ea8507f4388b7b5f","type":"prometheus-exporter","z":"cae39ee2.e2c898","name":"Boil temperature","metric":"f7b80ed39105d802","x":740,"y":100,"wires":[]},{"id":"f7b80ed39105d802","type":"prometheus-metric-config","name":"temp_boil","help":"Boil kettle temperaure","labels":"","mtype":"gauge"}]`
