### ISSUE TITLE
Metric name has already been registered

### ISSUE THREAD

**Issue by joeldz** [Docoyo/node-red-contrib-prometheus-exporter#5]
The prometheus out node works fine after I click deploy the first time with a new metric name, and the metric shows up on the /metrics page.

But if I click on deploy a second time it will give me two errors in the debug panel:
1. "Error: A metric with the name metric_name has already been registered."
2. "Missing metric configuration"

And the nodered /metrics page becomes blank.

**Comment by matterlobby** [comment]
Hi @joeldz , thank you very much for your feedback. I will have a look at it today.

**Comment by matterlobby** [comment]
@joeldz Bug fixed. Please update your node from the palette manager or by updating the npm. Thank you again for your feedback.
