### ISSUE TITLE
Feature Request: Add possibility to delete/clear a metric

### ISSUE THREAD

**Issue by stephanprantl-wh** [Docoyo/node-red-contrib-prometheus-exporter#8]
Hi,
for certain reasons we need to "delete" specific exposed metrics.
So it would be nice if you can add a "del" operation.

This operation should remove the currently exposed metric (minding the given labels) from the /metrics endpoint.
So that Prometheus doesn't retrieve a value.

example:
`{
    "op": "del",
    "labels": {
        "tag_1": "computer_123"
    }
}`

**Comment by matterlobby** [comment]
Unfortunately, removing a specific metric value for a label set is not supported by the underlying prom-client library. Only resetting all values could be supported.
